### ISSUE TITLE
go-echarts 开发讨论群

### ISSUE THREAD

**Issue by chenjiandongx** [chenjiandongx/go-echarts#3]
想参与到 go-echarts 到开发中来的同学或者对 go-echarts 感兴趣的同学可以扫码加群哈

![image_1](https://user-images.githubusercontent.com/19553554/54110857-6f168d00-441d-11e9-862e-2a70cb672a3d.png)

**Comment by wangxianzhuo** [comment]
你好，扫码提示二维码已过期

**Comment by chenjiandongx** [comment]
@wangxianzhuo 已更新
