### ISSUE TITLE
export to image

### ISSUE THREAD

**Issue by int3hh** [chenjiandongx/go-echarts#7]
Is possible to export chart to image ?

**Comment by chenjiandongx** [comment]
yes, but need other tools like selenium or phantom.js

**Comment by chfw** [comment]
Please have a look at these repos:

https://github.com/pyecharts/pyecharts-snapshot
https://github.com/chfw/echarts-scrappeteer

IMO, they are not go comands

**Comment by int3hh** [comment]
maybe you should consider native export implementation
